### ISSUE TITLE
system software requirements

### ISSUE THREAD

**Issue by mocart2** [yon2004/GraySquid#3]
Hi!
Can i set squid log to send data directly to graylog squid input, w/o rsyslog? like this:
`access_log tcp://192.168.15.18:19302`

**Comment by yon2004** [comment]
Hi @mocart2. 
I think the issue that I experianced back a long time ago when I wrote this up was that Squid would crash if it could not log sucsesfully. So using a local file and sending it from there allowed large bursts of trafic to not cause squid to crash. I have no idea if this is still a issue with squid or not but this was the solution that has worked great for me. 

Let me know if you get it working like this.
